AWSTemplateFormatVersion: 2010-09-09
Description: Create role and resouce
Parameters:
  BucketName:
    Type: String
    Default: "aws-example-sts-mk"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  StsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
            AWS: "arn:aws:iam::741181707369:user/sts-machine-user"
          Action:
          - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
           - s3:*
          Resource:
          - !Sub arn:aws:s3:::*
          - !Sub arn:aws:s3:::${BucketName}
          - !Sub arn:aws:s3:::${BucketName}/*
      Roles:
      - !Ref StsRole