#!/usr/bin/env bash

# Create a VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specification 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]' \
--region ap-south-1 \
--query Vpc.VpcId \
--output text)

echo "VPC ID:" $VPC_ID

# Modify VPC and enable hostname
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames

# Create a IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text)

echo "IGW ID:" $IGW_ID

# Attach IGW to VPC
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Create a Subnet
SUBNET_ID=$(aws ec2 create-subnet \
    --vpc-id $VPC_ID \
    --cidr-block "172.1.0.0/20" \
    --query Subnet.SubnetId \
    --output text)

echo "Subnet ID:" $SUBNET_ID

# Modify subnet attribute to auto assign public IP
aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch

# Get route table ID
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query RouteTables[0].RouteTableId \
--output text)

echo "RT ID:" $RT_ID

# Add route table with route to Subnet
aws ec2 associate-route-table \
    --route-table-id $RT_ID \
    --subnet-id $SUBNET_ID

# Add a route for our RT to or IGW
aws ec2 create-route \
    --route-table-id $RT_ID \
    --destination-cidr-block 0.0.0.0/0 \
    --gateway-id $IGW_ID

# print delete command
echo "./delete-vpc $VPC_ID $IGW_ID $SUBNET_ID $RT_ID"