#!/usr/bin/env bash
echo "== deploy s3 buket via CFN script"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region ap-south-1 \
--stack-name $STACK_NAME